version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: paderlol/nacos:latest
    volumes:
    - ./logs:/home/nacos/logs
    ports:
    - "8848:8848"
    - "9555:9555"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
    - mysql-master
    - mysql-slave

  nacos2:
    hostname: nacos2
    image: paderlol/nacos:latest
    container_name: nacos2
    ports:
    - "8849:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
    - mysql-master
    - mysql-slave
  nacos3:
    hostname: nacos3
    image: paderlol/nacos:latest
    container_name: nacos3
    ports:
    - "8850:8848"
    env_file:
      - ./env/nacos-hostname.env
    restart: always
    depends_on:
    - mysql-master
    - mysql-slave
  mysql-master:
    container_name: mysql-master
    image: paderlol/nacos-mysql-master:latest
    env_file:
      - ./env/mysql-common.env
      - ./env/mysql-master.env
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
  mysql-slave:
    container_name: mysql-slave
    image: paderlol/nacos-mysql-slave:latest
    env_file:
      - ./env/mysql-common.env
      - ./env/mysql-slave.env
    ports:
    - "3305:3306"
    depends_on:
      - mysql-master
